apiVersion: ray.io/v1
kind: RayService
metadata:
  name: llama3
spec:
  serveConfigV2: |
    applications:
      - name: llama3
        import_path: serve_app.main:llm_ray
        runtime_env:
          working_dir: "https://github.com/Banner-Wang/llm/archive/refs/heads/main.zip"
          pip: ["transformers==4.44.0","torch==2.3.1","fastapi==0.111.0","accelerate==0.33.0"]
        route_prefix: /
  rayClusterConfig:
    rayVersion: '2.31.0' # Should match the Ray version in the image of the containers
    ######################headGroupSpecs#################################
    # Ray head pod template.
    headGroupSpec:
      # The `rayStartParams` are used to configure the `ray start` command.
      # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
      # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
      rayStartParams:
        dashboard-host: '0.0.0.0'
      # Pod template
      template:
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray:2.31.0
            ports:
            - containerPort: 6379
              name: gcs
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            volumeMounts:
              - mountPath: /tmp/ray
                name: ray-logs
            resources:
              limits:
                cpu: "2"
                memory: "8G"
              requests:
                cpu: "2"
                memory: "8G"
          volumes:
            - name: ray-logs
              emptyDir: {}    
    workerGroupSpecs:
    # The pod replicas in this group typed worker
    - replicas: 1
      minReplicas: 1
      maxReplicas: 10
      groupName: gpu-group
      rayStartParams: {}
      # Pod template
      template:
        spec:
          containers:
          - name: ray-worker
            image: rayproject/ray:2.31.0
            resources:
              limits:
                cpu: 4
                memory: "16G"
                nvidia.com/gpu: 1
              requests:
                cpu: 3
                memory: "12G"
                nvidia.com/gpu: 1     
          # Please add the following taints to the GPU node.
          tolerations:
            - key: "nvidia.com/gpu.product"
              operator: "Equal"
              value: "NVIDIA-GeForce-RTX-3090"
              effect: "NoSchedule"
